apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "first-pool"
spec:
  blocks:
    - start:  {{ .Values.lbIPPool.start }} ##"192.168.50.240"
      stop: {{ .Values.lbIPPool.stop }} ## "192.168.50.249"