apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-targetallocator-rolebinding
  namespace:  {{ .Values.namespace.values.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opentelemetry-targetallocator-role
subjects:
- kind: ServiceAccount
  name: opentelemetry-metrics-collector-targetallocator
  namespace: {{ .Values.namespace.values.namespace.name }}
- kind: ServiceAccount
  name: opentelemetry-metrics-collector-collector
  namespace: {{ .Values.namespace.values.namespace.name }}