namespace:
  values:
    namespace:
      name: observability

prometheusOperatorCrds:
  source:
    url: https://github.com/prometheus-community/helm-charts.git
    targetRevision: prometheus-operator-crds-9.0.1
  values:
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true

grafana:
  source:
    url: https://github.com/grafana/helm-charts.git
    targetRevision: grafana-7.3.0
  values:
    revisionHistoryLimit: 0
    plugins:
      - grafana-googlesheets-datasource
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://thanos-query.observability.svc.cluster.local:9090
            access: proxy
            isDefault: true
            jsonData:
              queryTimeout: 120s
              timeInterval: 30s
              defaultEditor: "code"
              prometheusType: "Prometheus"
              prometheusVersion: "2.40.1"
    persistence:
      type: pvc
      enabled: true
      storageClassName: local-path
      accessModes:
        - ReadWriteOnce
      size: 5Gi
      finalizers:
        - kubernetes.io/pvc-protection
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hosts:
        - grafana.ntakashi.com
