namespace:
  values:
    namespace:
      name: observability

prometheusOperatorCrds:
  source:
    url: https://github.com/prometheus-community/helm-charts.git
    targetRevision: prometheus-operator-crds-4.0.0
  values:
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true

grafana:
  source:
    url: https://github.com/grafana/helm-charts.git
    targetRevision: grafana-6.57.0
  values:
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-prometheus.observability.svc.cluster.local:9090
            access: proxy
            isDefault: true
            scrape_intervall: "30s"
    persistence:
      type: pvc
      enabled: true
      storageClassName: local-path
      accessModes:
        - ReadWriteOnce
      size: 5Gi
      finalizers:
        - kubernetes.io/pvc-protection
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hosts:
        - grafana.ntakashi.com
