opentelemetry-collector:
  mode: "deployment"
  config:
    receivers:
      jaeger: null
      zipkin: null
      prometheus:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 15s
              static_configs:
                - targets:
                    - ${env:MY_POD_IP}:8888
    pipelines:
      logs: null
      metrics:
        exporters:
          - debug
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
          - prometheus
      traces: null
