opentelemetry-collector:
  mode: "deployment"
  image:
    # If you want to use the core image `otel/opentelemetry-collector`, you also need to change `command.name` value to `otelcol`.
    repository: "otel/opentelemetry-collector-contrib"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
    # When digest is set to a non-empty value, images will be pulled by digest (regardless of tag value).
    digest: ""

  extraEnvs:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name

  config:
    receivers:
      jaeger: null
      zipkin: null
      prometheus:
        target_allocator:
          endpoint: http://opentelemetry-target-allocator.observability.svc.cluster.local:80
          interval: 30s
          collector_id: ${env:MY_POD_NAME}
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 15s
              static_configs:
                - targets:
                    - ${env:MY_POD_IP}:8888
    service:
      pipelines:
        logs: null
        metrics:
          exporters:
            - debug
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
            - prometheus
        traces: null
