{{- if .Values.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.namespace.values.namespace.name }}-namespace
  namespace: {{ .Values.namespace.values.namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "300"
spec:
  destination:
    namespace: {{ .Values.namespace.values.namespace.name }}
    server: https://kubernetes.default.svc
  project: apps-project
  source:
    helm:
      releaseName: {{ .Values.namespace.values.namespace.name }}-namespace
      {{- with .Values.namespace.values }}
      values: | 
        {{- toYaml . | nindent 8 }}
      {{- end }}
    repoURL: https://github.com/nicolastakashi/homelab.git
    targetRevision: HEAD
    path: ./argo/namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
      backoff:
        duration: 15s
        factor: 1
{{- end }}