perses:
  config:
    frontend:
      explore:
        enabled: true

  ingress:
    enabled: true

    hosts:
      - host: perses.ntakashi.com
        paths:
          - path: /
            pathType: Prefix

    ingressClassName: "cilium"

  sidecar:
    enabled: true
