apps:
  - name: argocd
    namespace: argocd-system
    source:
      targetRevision: HEAD
      url: https://github.com/nicolastakashi/homelab.git
      path: ./argo/apps/argocd
  - name: cilium
    namespace: cilium-system
    source:
      targetRevision: HEAD
      url: https://github.com/nicolastakashi/homelab.git
      path: ./argo/apps/cilium
