k3s-control-plane:
  description: "kubernetes control-plane"
  target_node: cabral
  vmid: 201
  clone: "ubuntu-server-jammy"
  tags: "k8s,k8s-control-plane"
  resources:
    cpu: 2
    memory: 2048
    disk: 20G
k3s-worker-node-01:
  description: "kubernetes worker-node-01"
  target_node: cabral
  vmid: 202
  clone: "ubuntu-server-jammy"
  tags: "k8s,k8s-worker-node"
  resources:
    cpu: 2
    memory: 2048
    disk: 20G
k3s-worker-node-02:
  description: "kubernetes worker-node-02"
  target_node: cabral
  vmid: 203
  clone: "ubuntu-server-jammy"
  tags: "k8s,k8s-worker-node"
  resources:
    cpu: 2
    memory: 2048
    disk: 20G
