kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.waves.namespace | quote }}
  {{- if .Values.namespace.annotations }}
  {{- range $key, $value := .Values.namespace.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.namespace.labels }}
  labels:
  {{- range $key, $value := .Values.namespace.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}