{{- if and (.Values.enabled) (not (.Values.serviceAccount)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opentelemetry-collector.serviceAccountName" . }}-targetallocator
  labels:
    {{- include "opentelemetry-target-allocator.labels" . | nindent 4 }}
{{ end }}