apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector-stateful
  namespace: {{ .Values.namespace.values.namespace.name }}
spec:
  mode: statefulset
  targetAllocator:
    enabled: true
    serviceAccount: opentelemetry-collector-stateful-targetallocator
    prometheusCR:
      enabled: true
  config: |
    receivers:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 10s
            static_configs:
            - targets: [ '0.0.0.0:8888' ]

    extensions:
      zpages:

    processors:

    exporters:
      debug:
      prometheusremotewrite:
        endpoint: "http://thanos-receive.observability.svc.cluster.local:19291/api/v1/push"
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: 
            - prometheus
          processors: []
          exporters:
            - prometheusremotewrite