kube-prometheus-stack:
  fullnameOverride: "prometheus-operator"
  crds:
    enabled: false

  defaultRules:
    create: false

  alertmanager:
    enabled: false

  grafana:
    enabled: false

  kubeStateMetrics:
    enabled: false

  nodeExporter:
    enabled: false

  prometheusOperator:
    kubeletEndpointsEnabled: false
    kubeletEndpointSliceEnabled: true

  kubelet:
    serviceMonitor:
      relabelings:
        - action: replace
          sourceLabels: [__metrics_path__]
          targetLabel: metrics_path
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: k8s_pod_name
        - action: labeldrop
          regex: "pod"
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: k8s_namespace_name
        - action: labeldrop
          regex: "namespace"
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: k8s_service_name
        - action: labeldrop
          regex: "service"
        - sourceLabels: [job]
          targetLabel: service_name
        - sourceLabels: [node]
          targetLabel: k8s_node_name
        - action: labeldrop
          regex: "node"

      cAdvisorRelabelings:
        - action: replace
          sourceLabels: [__metrics_path__]
          targetLabel: metrics_path
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: k8s_pod_name
        - action: labeldrop
          regex: "pod"
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: k8s_namespace_name
        - action: labeldrop
          regex: "namespace"
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: k8s_service_name
        - action: labeldrop
          regex: "service"
        - sourceLabels: [job]
          targetLabel: service_name
        - sourceLabels: [node]
          targetLabel: k8s_node_name
        - action: labeldrop
          regex: "node"

      probesRelabelings:
        - action: replace
          sourceLabels: [__metrics_path__]
          targetLabel: metrics_path
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: k8s_pod_name
        - action: labeldrop
          regex: "pod"
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: k8s_namespace_name
        - action: labeldrop
          regex: "namespace"
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: k8s_service_name
        - action: labeldrop
          regex: "service"
        - sourceLabels: [job]
          targetLabel: service_name
        - sourceLabels: [node]
          targetLabel: k8s_node_name
        - action: labeldrop
          regex: "node"

      resourceRelabelings:
        - action: replace
          sourceLabels: [__metrics_path__]
          targetLabel: metrics_path
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: k8s_pod_name
        - action: labeldrop
          regex: "pod"
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: k8s_namespace_name
        - action: labeldrop
          regex: "namespace"
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: k8s_service_name
        - action: labeldrop
          regex: "service"
        - sourceLabels: [job]
          targetLabel: service_name
        - sourceLabels: [node]
          targetLabel: k8s_node_name
        - action: labeldrop
          regex: "node"

  prometheus:
    enabled: false
