apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opentelemetry-agent-collector-rolebinding
  namespace:  {{ .Values.namespace.values.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opentelemetry-agent-collector
subjects:
- kind: ServiceAccount
  name: opentelemetry-agent-collector
  namespace: {{ .Values.namespace.values.namespace.name }}
