apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/nicolastakashi/homelab.git
        revision: v3
        files:
          - path: provision/argocd/**/config.json
  template:
    metadata:
      name: "{{ .name }}"
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=true
        argocd.argoproj.io/sync-wave: "{{ .wave }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/nicolastakashi/homelab.git
        targetRevision: v3
        path: "{{ .dir }}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: -1
          backoff:
            duration: 15s
            factor: 1
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
