apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: "argocd-system"
  annotations:
    argocd.argoproj.io/sync-wave: "600"
spec:
  destination:
    namespace: {{ .Values.namespace.values.namespace.name  }}
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: "prometheus-operator"
    repoURL: https://github.com/nicolastakashi/homelab.git
    targetRevision: HEAD
    path: ./charts/prometheus-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
