opentelemetry-collector:
  mode: "daemonset"
  image:
    repository: "otel/opentelemetry-collector-contrib"
    pullPolicy: IfNotPresent

  clusterRole:
    rules:
      - apiGroups: [""]
        resources: ["nodes"]
        verbs: ["get", "list"]

  presets:
    hostMetrics:
      enabled: true
    kubernetesAttributes:
      enabled: true

  config:
    exporters:
      prometheusremotewrite:
        endpoint: "http://thanos-receive.observability.svc.cluster.local:19291/api/v1/receive"
        external_labels:
          cluster: "pt-north-1"
        tls:
          insecure: true

    processors:
      resourcedetection:
        detectors: [env, system, k8snode]
        timeout: 2s
        override: false
      transform:
        metric_statements:
          - context: datapoint
            statements:
              - set(attributes["k8s.container.name"], resource.attributes["k8s.container.name"])
              - set(attributes["k8s.namespace.name"], resource.attributes["k8s.namespace.name"])
              - set(attributes["k8s.pod.name"], resource.attributes["k8s.pod.name"])
    receivers:
      jaeger: null
      zipkin: null
      prometheus:
        config:
          scrape_configs:
            - job_name: opentelemetry-agent-collector
              scrape_interval: 15s
              static_configs:
                - targets:
                    - ${env:MY_POD_IP}:8888
    service:
      pipelines:
        logs: null
        metrics:
          exporters:
            - prometheusremotewrite
          processors:
            - resourcedetection
            - transform
            - memory_limiter
            - batch
          receivers:
            - otlp
            - prometheus
        traces: null
