opentelemetry-collector:
  mode: "daemonset"
  image:
    repository: "otel/opentelemetry-collector-contrib"
    pullPolicy: IfNotPresent

  presets:
    hostMetrics:
      enabled: true
    kubernetesAttributes:
      enabled: true

  config:
    exporters:
      prometheusremotewrite:
        endpoint: "http://thanos-receive.observability.svc.cluster.local:19291/api/v1/receive"
        external_labels:
          cluster: "pt-north-1"
        tls:
          insecure: true

    processors:
      resourcedetection/env:
        detectors: [env]
        timeout: 2s
        override: false
    receivers:
      jaeger: null
      zipkin: null
      prometheus:
        config:
          scrape_configs:
            - job_name: opentelemetry-agent-collector
              scrape_interval: 15s
              static_configs:
                - targets:
                    - ${env:MY_POD_IP}:8888
    service:
      pipelines:
        logs: null
        metrics:
          exporters:
            - prometheusremotewrite
          processors:
            - resourcedetection/env
            - memory_limiter
            - batch
          receivers:
            - otlp
            - prometheus
        traces: null
