enabled: true

namespace:
  values:
    namespace:
      name: argocd-system

argocd:
  source:
    url: https://github.com/argoproj/argo-helm.git
    targetRevision: argo-cd-5.34.1
  values:
    global:
      revisionHistoryLimit: 0
      logging:
        format: json
        level: warn
    dex:
      enabled: false
    server:
      extraArgs:
        - --insecure

      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - argocd.ntakashi.com
