{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}
  namespace: {{ template "opentelemetry-collector.namespace" . }}
  labels:
    {{- include "opentelemetry-target-allocator.labels" . | nindent 4 }}
    component: target-allocator
    {{- range $key, $value := .Values.serviceMonitor.extraLabels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
spec:
  endpoints:
  - honorLabels: true
    port: targetallocation
  selector:
    matchLabels:
      {{- include "opentelemetry-target-allocator.selectorLabels" . | nindent 6 }}
      component: target-allocator
{{- end }}