---
- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download

- hosts: k3s_control_plane
  become: yes
  roles:
    - role: helm
    - role: k3s/control_plane
    - role: argocd

- hosts: k3s_worker_node
  become: yes
  roles:
    - role: k3s/worker_node
