apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'thanos'
  namespace: "argocd-system"
  annotations:
    argocd.argoproj.io/sync-wave: "600"
spec:
  destination:
    namespace: {{ .Values.namespace.values.namespace.name  }}
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: thanos
      {{- with .Values.thanos.values }}
      values: |
        {{- toYaml . | nindent 8 }}
      {{- end }}
    repoURL: registry-1.docker.io/bitnamicharts
    chart: thanos
    targetRevision: 12.11.1
    # path: ./bitnami/thanos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1