- name: Loading bashrc
  shell: . ~/.bashrc  && echo $GIT_TOKEN
  args: 
    executable: /bin/bash
  register: git_token
  
- name: Copy Git Repo Secret
  template:
    src: "homelabsecret.j2"
    dest: "/tmp/homelabsecret.yaml"
    owner: root
    group: root
    mode: 0755