- name: Loading bashrc
  shell: source ~{{ ansible_user }}/.bashrc  && echo $GIT_TOKEN
  args: 
    executable: /bin/bash
  register: git_token

- name: Basic usage
  ansible.builtin.debug:
    msg: "{{ git_token.stdout }}"
    
- name: Copy Git Repo Secret
  template:
    src: "homelabsecret.j2"
    dest: "/tmp/homelabsecret.yaml"
    owner: root
    group: root
    mode: 0755