namespace:
  values:
    namespace:
      name: observability

thanos:
  source:
    url: https://github.com/bitnami/charts.git
    targetRevision: main
  values:
    existingObjstoreSecret: thanos-storage-config
    queryFrontEnd:
      enabled: false
