namespace:
  values:
    namespace:
      name: observability

thanos:
  source:
    url: registry-1.docker.io/bitnamicharts
    targetRevision: 13.3.0
  values:
    existingObjstoreSecret: thanos-storage-config
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 30s

    queryFrontend:
      enabled: false

    query:
      logFormat: json
      extraFlags:
        - --grpc-grace-period=20s
        - --http-grace-period=20s
        - --query.auto-downsampling
        - --query.default-step=30s
        - --query.metadata.default-time-range=5m
        - --store.limits.request-series=500000
        - --store.response-timeout=1m59s

    receive:
      enabled: true

      logFormat: json

      tsdbRetention: 3h

      replicaCount: 2

      extraFlags:
        - --hash-func=SHA256
        - --receive.grpc-compression=snappy
        - --receive.hashrings-algorithm=ketama

    compactor:
      enabled: true
      retentionResolutionRaw: 15d
      retentionResolution5m: 30d
      retentionResolution1h: 60d

      extraFlags:
        - --hash-func=SHA256
