namespace:
  values:
    namespace:
      name: observability

thanos:
  source:
    url: registry-1.docker.io/bitnamicharts
    targetRevision: 12.13.13
  values:
    existingObjstoreSecret: thanos-storage-config

    queryFrontend:
      enabled: false

    query:
      logFormat: json

    receive:
      enabled: true

      logFormat: json

      tsdbRetention: 3h

      replicaCount: 1
