namespace:
  values:
    namespace:
      name: observability

grafana:
  source:
    url: https://github.com/bitnami/charts.git
    targetRevision: main
  values:
    existingObjstoreSecret: thanos-storage-config
