namespace:
  values:
    namespace:
      name: opentelemetry-operator

openTelemetryOperator:
  source:
    url: https://github.com/open-telemetry/opentelemetry-helm-charts.git
    targetRevision: opentelemetry-operator-0.48.0
  values:
    manager:
      serviceMonitor:
        enabled: true
    admissionWebhooks:
      certManager:
        enabled: true
