thanos:
  fullnameOverride: "thanos"
  objstoreConfig: |
    type: FILESYSTEM
    config:
      directory: "/srv/thanos"

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: k8s_pod_name
        - action: labeldrop
          regex: "pod"
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: k8s_namespace_name
        - action: labeldrop
          regex: "namespace"
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: k8s_service_name
        - action: labeldrop
          regex: "service"
        - sourceLabels: [__meta_kubernetes_pod_container_name]
          targetLabel: k8s_container_name
        - action: labeldrop
          regex: "container"
        - sourceLabels: [job]
          targetLabel: service_name

  query:
    revisionHistoryLimit: 0
    logFormat: json
    logLevel: warn

  queryFrontend:
    revisionHistoryLimit: 0
    logFormat: json
    logLevel: warn

  receive:
    enabled: true
    logFormat: json
    mode: dual-mode
    logLevel: warn
    tsdbRetention: 4h
    replicaCount: 3
    replicationFactor: 2
    resourcesPreset: small
    service:
      additionalHeadless: true

  receiveDistributor:
    enabled: true
    revisionHistoryLimit: 0
    logFormat: json
    logLevel: warn
